/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.trungnguyen.kafka.demo.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Avenger extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8832067225972588483L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Avenger\",\"namespace\":\"com.trungnguyen.kafka.demo.model\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"real_name\",\"type\":\"string\"},{\"name\":\"movies\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Avenger> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Avenger> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Avenger> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Avenger> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Avenger> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Avenger to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Avenger from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Avenger instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Avenger fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence name;
  private java.lang.CharSequence real_name;
  private java.util.List<java.lang.CharSequence> movies;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Avenger() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param real_name The new value for real_name
   * @param movies The new value for movies
   */
  public Avenger(java.lang.CharSequence name, java.lang.CharSequence real_name, java.util.List<java.lang.CharSequence> movies) {
    this.name = name;
    this.real_name = real_name;
    this.movies = movies;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return real_name;
    case 2: return movies;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: real_name = (java.lang.CharSequence)value$; break;
    case 2: movies = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'real_name' field.
   * @return The value of the 'real_name' field.
   */
  public java.lang.CharSequence getRealName() {
    return real_name;
  }


  /**
   * Sets the value of the 'real_name' field.
   * @param value the value to set.
   */
  public void setRealName(java.lang.CharSequence value) {
    this.real_name = value;
  }

  /**
   * Gets the value of the 'movies' field.
   * @return The value of the 'movies' field.
   */
  public java.util.List<java.lang.CharSequence> getMovies() {
    return movies;
  }


  /**
   * Sets the value of the 'movies' field.
   * @param value the value to set.
   */
  public void setMovies(java.util.List<java.lang.CharSequence> value) {
    this.movies = value;
  }

  /**
   * Creates a new Avenger RecordBuilder.
   * @return A new Avenger RecordBuilder
   */
  public static com.trungnguyen.kafka.demo.model.Avenger.Builder newBuilder() {
    return new com.trungnguyen.kafka.demo.model.Avenger.Builder();
  }

  /**
   * Creates a new Avenger RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Avenger RecordBuilder
   */
  public static com.trungnguyen.kafka.demo.model.Avenger.Builder newBuilder(com.trungnguyen.kafka.demo.model.Avenger.Builder other) {
    if (other == null) {
      return new com.trungnguyen.kafka.demo.model.Avenger.Builder();
    } else {
      return new com.trungnguyen.kafka.demo.model.Avenger.Builder(other);
    }
  }

  /**
   * Creates a new Avenger RecordBuilder by copying an existing Avenger instance.
   * @param other The existing instance to copy.
   * @return A new Avenger RecordBuilder
   */
  public static com.trungnguyen.kafka.demo.model.Avenger.Builder newBuilder(com.trungnguyen.kafka.demo.model.Avenger other) {
    if (other == null) {
      return new com.trungnguyen.kafka.demo.model.Avenger.Builder();
    } else {
      return new com.trungnguyen.kafka.demo.model.Avenger.Builder(other);
    }
  }

  /**
   * RecordBuilder for Avenger instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Avenger>
    implements org.apache.avro.data.RecordBuilder<Avenger> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence real_name;
    private java.util.List<java.lang.CharSequence> movies;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.trungnguyen.kafka.demo.model.Avenger.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.real_name)) {
        this.real_name = data().deepCopy(fields()[1].schema(), other.real_name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.movies)) {
        this.movies = data().deepCopy(fields()[2].schema(), other.movies);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Avenger instance
     * @param other The existing instance to copy.
     */
    private Builder(com.trungnguyen.kafka.demo.model.Avenger other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.real_name)) {
        this.real_name = data().deepCopy(fields()[1].schema(), other.real_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.movies)) {
        this.movies = data().deepCopy(fields()[2].schema(), other.movies);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.trungnguyen.kafka.demo.model.Avenger.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.trungnguyen.kafka.demo.model.Avenger.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'real_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getRealName() {
      return real_name;
    }


    /**
      * Sets the value of the 'real_name' field.
      * @param value The value of 'real_name'.
      * @return This builder.
      */
    public com.trungnguyen.kafka.demo.model.Avenger.Builder setRealName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.real_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'real_name' field has been set.
      * @return True if the 'real_name' field has been set, false otherwise.
      */
    public boolean hasRealName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'real_name' field.
      * @return This builder.
      */
    public com.trungnguyen.kafka.demo.model.Avenger.Builder clearRealName() {
      real_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'movies' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getMovies() {
      return movies;
    }


    /**
      * Sets the value of the 'movies' field.
      * @param value The value of 'movies'.
      * @return This builder.
      */
    public com.trungnguyen.kafka.demo.model.Avenger.Builder setMovies(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[2], value);
      this.movies = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'movies' field has been set.
      * @return True if the 'movies' field has been set, false otherwise.
      */
    public boolean hasMovies() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'movies' field.
      * @return This builder.
      */
    public com.trungnguyen.kafka.demo.model.Avenger.Builder clearMovies() {
      movies = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Avenger build() {
      try {
        Avenger record = new Avenger();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.real_name = fieldSetFlags()[1] ? this.real_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.movies = fieldSetFlags()[2] ? this.movies : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Avenger>
    WRITER$ = (org.apache.avro.io.DatumWriter<Avenger>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Avenger>
    READER$ = (org.apache.avro.io.DatumReader<Avenger>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeString(this.real_name);

    long size0 = this.movies.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.movies) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.real_name = in.readString(this.real_name instanceof Utf8 ? (Utf8)this.real_name : null);

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.movies;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("movies").schema());
        this.movies = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          this.real_name = in.readString(this.real_name instanceof Utf8 ? (Utf8)this.real_name : null);
          break;

        case 2:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.movies;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("movies").schema());
            this.movies = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










